declare namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_GISUS_CATEGORY_ID: string;
		NEXT_PUBLIC_GISUS_REPO_ID: string;
		NEXT_PUBLIC_KEYSTATIC_REPO: string;
		NEXT_PUBLIC_KEYSTATIC_OWNER: string;
		NEXT_PUBLIC_KEYSTATIC_GITHUB_APP_SLUG: string;
		GITHUB_PAT: string;
		KEYSTATIC_GITHUB_CLIENT_ID: string;
		KEYSTATIC_GITHUB_CLIENT_SECRET: string;
		KEYSTATIC_SECRET: string;
		HOST_URL: string;
	}
}
