import { FaDatabase, FaFileCsv } from "react-icons/fa6";
import { FiFileText } from "react-icons/fi";
import type { IconType } from "react-icons/lib";
import { RiJavaFill, RiTerminalBoxLine } from "react-icons/ri";
import {
	SiCplusplus,
	SiCss3,
	SiDocker,
	SiDotenv,
	SiDotnet,
	SiGnubash,
	SiGo,
	SiGraphql,
	SiHtml5,
	SiJavascript,
	SiJson,
	SiKotlin,
	SiMdx,
	SiMermaid,
	SiNginx,
	SiPostcss,
	SiPython,
	SiReact,
	SiRust,
	SiSolidity,
	SiSvelte,
	SiSwift,
	SiToml,
	SiTypescript,
	SiVuedotjs,
	SiYaml,
} from "react-icons/si";

export const EDITOR_LANG_OPTIONS = [
	{
		label: "TypeScript",
		value: "ts-tags",
		depth: 1,
		icon: SiTypescript,
		color: "#3178C6",
		commentPrefix: "//",
	},
	{
		label: "React",
		value: "tsx",
		depth: 1,
		icon: SiReact,
		color: "#61DAFB",
		commentPrefix: "//",
	},
	{
		label: "CSS/SCSS",
		value: "scss",
		depth: 1,
		icon: SiCss3,
		color: "#CF649A",
		commentPrefix: "//",
	},
	{
		label: "Python",
		value: "python",
		depth: 1,
		icon: SiPython,
		color: "#3776AB",
		commentPrefix: "#",
	},
	{
		label: "Solidity",
		value: "solidity",
		depth: 1,
		icon: SiSolidity,
		color: "#363636",
		commentPrefix: "//",
	},
	{
		label: "JSON",
		value: "jsonc",
		depth: 1,
		icon: SiJson,
		color: "#F1E05A",
		commentPrefix: "//",
	},
	{
		label: "YAML",
		value: "yaml",
		depth: 1,
		icon: SiYaml,
		color: "#CB171E",
		commentPrefix: "#",
	},
	{
		label: "Bash",
		value: "bash",
		depth: 1,
		icon: SiGnubash,
		color: "#4EAA25",
		commentPrefix: "#",
	},
	{
		label: "Plain Text",
		value: "text",
		depth: 1,
		icon: FiFileText,
		color: "#64748B",
		commentPrefix: "//",
	},

	{
		label: "JavaScript",
		value: "javascript",
		depth: 2,
		group: "웹 생태계",
		icon: SiJavascript,
		color: "#F7DF1E",
		commentPrefix: "//",
	},
	{
		label: "Vue",
		value: "vue",
		depth: 2,
		group: "웹 생태계",
		icon: SiVuedotjs,
		color: "#42B883",
		commentPrefix: "//",
	},
	{
		label: "Svelte",
		value: "svelte",
		depth: 2,
		group: "웹 생태계",
		icon: SiSvelte,
		color: "#FF3E00",
		commentPrefix: "//",
	},

	{
		label: "HTML",
		value: "html",
		depth: 2,
		group: "마크업 & 스타일",
		icon: SiHtml5,
		color: "#E34F26",
		commentPrefix: "<!--",
		commentPostfix: " -->",
	},
	{
		label: "PostCSS",
		value: "postcss",
		depth: 2,
		group: "마크업 & 스타일",
		icon: SiPostcss,
		color: "#DD3A0A",
		commentPrefix: "/*",
		commentPostfix: " */",
	},

	{
		label: "Go",
		value: "go",
		depth: 2,
		group: "서버 & 시스템",
		icon: SiGo,
		color: "#00ADD8",
		commentPrefix: "//",
	},
	{
		label: "Rust",
		value: "rust",
		depth: 2,
		group: "서버 & 시스템",
		icon: SiRust,
		color: "#DEA584",
		commentPrefix: "//",
	},
	{
		label: "Java",
		value: "java",
		depth: 2,
		group: "서버 & 시스템",
		icon: RiJavaFill,
		color: "#007396",
		commentPrefix: "//",
	},
	{
		label: "Kotlin",
		value: "kotlin",
		depth: 2,
		group: "서버 & 시스템",
		icon: SiKotlin,
		color: "#7F52FF",
		commentPrefix: "//",
	},
	{
		label: "C / C++",
		value: "cpp",
		depth: 2,
		group: "서버 & 시스템",
		icon: SiCplusplus,
		color: "#00599C",
		commentPrefix: "//",
	},
	{
		label: "C#",
		value: "csharp",
		depth: 2,
		group: "서버 & 시스템",
		icon: SiDotnet,
		color: "#512BD4",
		commentPrefix: "//",
	},
	{
		label: "Swift",
		value: "swift",
		depth: 2,
		group: "서버 & 시스템",
		icon: SiSwift,
		color: "#FA7343",
		commentPrefix: "//",
	},

	{
		label: "TOML",
		value: "toml",
		depth: 2,
		group: "데이터 & 설정",
		icon: SiToml,
		color: "#9C4221",
		commentPrefix: "#",
	},
	{
		label: "CSV",
		value: "csv",
		depth: 2,
		group: "데이터 & 설정",
		icon: FaFileCsv,
		color: "#2F9D27",
		commentPrefix: "#",
	},
	{
		label: "Markdown/MDX",
		value: "mdx",
		depth: 2,
		group: "데이터 & 설정",
		icon: SiMdx,
		color: "#F9AC00",
		commentPrefix: "<!--",
		commentPostfix: " -->",
	},
	{
		label: "SQL",
		value: "sql",
		depth: 2,
		group: "데이터 & 설정",
		icon: FaDatabase,
		color: "#336791",
		commentPrefix: "--",
	},
	{
		label: "GraphQL",
		value: "graphql",
		depth: 2,
		group: "데이터 & 설정",
		icon: SiGraphql,
		color: "#E10098",
		commentPrefix: "#",
	},

	{
		label: "PowerShell",
		value: "powershell",
		depth: 2,
		group: "인프라 & 도구",
		icon: RiTerminalBoxLine,
		color: "#5391FE",
		commentPrefix: "#",
	},
	{
		label: "Dockerfile",
		value: "docker",
		depth: 2,
		group: "인프라 & 도구",
		icon: SiDocker,
		color: "#2496ED",
		commentPrefix: "#",
	},
	{
		label: "Nginx",
		value: "nginx",
		depth: 2,
		group: "인프라 & 도구",
		icon: SiNginx,
		color: "#009639",
		commentPrefix: "#",
	},
	{
		label: "Env",
		value: "dotenv",
		depth: 2,
		group: "인프라 & 도구",
		icon: SiDotenv,
		color: "#ECD53F",
		commentPrefix: "#",
	},
	{
		label: "Mermaid",
		value: "mermaid",
		depth: 2,
		group: "인프라 & 도구",
		icon: SiMermaid,
		color: "#FF3670",
		commentPrefix: "%%",
	},
] as const satisfies ReadonlyArray<{
	label: string;
	value: string;
	depth: 1 | 2;
	group?: string;
	icon: IconType;
	color: string;
	commentPrefix: string;
	commentPostfix?: string;
}>;

export type EditorCodeLang = (typeof EDITOR_LANG_OPTIONS)[number]["value"];
export type EditorLangOption = (typeof EDITOR_LANG_OPTIONS)[number];

export const EDITOR_CODE_BLOCK_NAME = "CodeBlock";
export const EDITOR_CODE_BLOCK_THEME = "one-dark-pro" as const;
